-- SAVOR POS Supabase setup
-- Run this in Supabase Dashboard > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  role text not null check (role in ('admin', 'cashier', 'waiter', 'kitchen')),
  phone text,
  email text unique,
  shift_start time,
  shift_end time,
  avatar_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.restaurant_tables (
  id integer generated by default as identity primary key,
  table_number integer not null unique,
  capacity integer not null default 4,
  status text not null default 'available'
    check (status in ('available', 'ordered', 'preparing', 'ready', 'occupied', 'billed')),
  current_order_id uuid,
  position_x double precision default 0,
  position_y double precision default 0,
  updated_at timestamptz not null default now()
);

-- Migration for existing tables:
alter table public.restaurant_tables add column if not exists position_x double precision default 0;
alter table public.restaurant_tables add column if not exists position_y double precision default 0;

create table if not exists public.menu_categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  icon text,
  color text,
  sort_order integer not null default 0,
  is_active boolean not null default true
);

create table if not exists public.menu_items (
  id uuid primary key default gen_random_uuid(),
  category_id uuid references public.menu_categories(id) on delete set null,
  name text not null,
  description text,
  price numeric(10,2) not null default 0,
  prep_time_minutes integer not null default 10,
  image_url text,
  is_available boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  table_id integer references public.restaurant_tables(id) on delete set null,
  customer_name text,
  order_type text not null default 'dine_in' check (order_type in ('dine_in', 'takeaway')),
  status text not null default 'pending'
    check (status in ('draft', 'pending', 'preparing', 'ready', 'served', 'billed', 'cancelled')),
  subtotal numeric(10,2) not null default 0,
  cgst numeric(10,2) not null default 0,
  sgst numeric(10,2) not null default 0,
  service_charge numeric(10,2) not null default 0,
  discount numeric(10,2) not null default 0,
  total numeric(10,2) not null default 0,
  payment_method text check (payment_method is null or payment_method in ('cash', 'upi', 'card', 'wallet', 'Cash', 'UPI', 'Card')),
  payment_amount numeric(10,2),
  change_amount numeric(10,2),
  payment_status text default 'unpaid' check (payment_status in ('unpaid', 'paid')),
  coupon_code text,
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.restaurant_tables
  add constraint restaurant_tables_current_order_id_fkey
  foreign key (current_order_id) references public.orders(id) on delete set null
  deferrable initially deferred;

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  menu_item_id uuid references public.menu_items(id) on delete set null,
  name text not null,
  price numeric(10,2) not null default 0,
  quantity integer not null default 1,
  notes text,
  status text not null default 'pending'
    check (status in ('pending', 'preparing', 'ready', 'served'))
);

create table if not exists public.inventory (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  unit text not null default 'kg',
  current_stock numeric(10,2) not null default 0,
  minimum_stock numeric(10,2) not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.purchase_records (
  id uuid primary key default gen_random_uuid(),
  inventory_id uuid not null references public.inventory(id) on delete cascade,
  quantity numeric(10,2) not null default 0,
  supplier text,
  cost numeric(10,2) not null default 0,
  purchased_at timestamptz not null default now()
);

create table if not exists public.coupons (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  discount_type text not null check (discount_type in ('percent', 'flat')),
  discount_value numeric(10,2) not null default 0,
  min_order_value numeric(10,2) not null default 0,
  max_uses integer not null default 0,
  used_count integer not null default 0,
  is_active boolean not null default true,
  expires_at timestamptz
);

create table if not exists public.app_settings (
  id uuid primary key default gen_random_uuid(),
  restaurant_name text not null default 'SAVOR Kitchen',
  address text,
  phone text,
  gstin text,
  cgst_rate numeric(5,2) not null default 2.5,
  sgst_rate numeric(5,2) not null default 2.5,
  service_charge_rate numeric(5,2) not null default 5,
  service_charge_enabled boolean not null default true,
  currency_symbol text not null default '₹',
  receipt_template integer not null default 1,
  logo_url text,
  updated_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  body text not null,
  type text not null,
  target_role text check (target_role is null or target_role in ('admin', 'cashier', 'waiter', 'kitchen')),
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists set_tables_updated_at on public.restaurant_tables;
create trigger set_tables_updated_at
before update on public.restaurant_tables
for each row execute function public.set_updated_at();

drop trigger if exists set_menu_items_updated_at on public.menu_items;
create trigger set_menu_items_updated_at
before update on public.menu_items
for each row execute function public.set_updated_at();

drop trigger if exists set_orders_updated_at on public.orders;
create trigger set_orders_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

drop trigger if exists set_inventory_updated_at on public.inventory;
create trigger set_inventory_updated_at
before update on public.inventory
for each row execute function public.set_updated_at();

drop trigger if exists set_app_settings_updated_at on public.app_settings;
create trigger set_app_settings_updated_at
before update on public.app_settings
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data->>'role', 'waiter')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.restaurant_tables enable row level security;
alter table public.menu_categories enable row level security;
alter table public.menu_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.inventory enable row level security;
alter table public.purchase_records enable row level security;
alter table public.coupons enable row level security;
alter table public.app_settings enable row level security;
alter table public.notifications enable row level security;

create policy "authenticated read profiles" on public.profiles
for select to authenticated using (true);
create policy "authenticated manage profiles" on public.profiles
for all to authenticated using (true) with check (true);

create policy "authenticated manage tables" on public.restaurant_tables
for all to authenticated using (true) with check (true);
create policy "authenticated manage categories" on public.menu_categories
for all to authenticated using (true) with check (true);
create policy "authenticated manage menu items" on public.menu_items
for all to authenticated using (true) with check (true);
create policy "authenticated manage orders" on public.orders
for all to authenticated using (true) with check (true);
create policy "authenticated manage order items" on public.order_items
for all to authenticated using (true) with check (true);
create policy "authenticated manage inventory" on public.inventory
for all to authenticated using (true) with check (true);
create policy "authenticated manage purchase records" on public.purchase_records
for all to authenticated using (true) with check (true);
create policy "authenticated manage coupons" on public.coupons
for all to authenticated using (true) with check (true);
create policy "authenticated manage app settings" on public.app_settings
for all to authenticated using (true) with check (true);
create policy "authenticated manage notifications" on public.notifications
for all to authenticated using (true) with check (true);

insert into public.restaurant_tables (table_number, capacity, status)
select n, case when n in (11, 19) then 8 when n in (6, 15) then 6 else 4 end, 'available'
from generate_series(1, 0) as n
on conflict (table_number) do nothing;

insert into public.menu_categories (name, icon, color, sort_order, is_active) values
('Starters', 'appetizer', '#EF4444', 1, true),
('Main Course', 'restaurant', '#F59E0B', 2, true),
('Beverages', 'local_cafe', '#3B82F6', 3, true),
('Desserts', 'cake', '#EC4899', 4, true),
('Combos', 'dining', '#22C55E', 5, true)
on conflict do nothing;

insert into public.inventory (name, unit, current_stock, minimum_stock) values
('Basmati Rice', 'kg', 45, 10),
('Wheat Flour', 'kg', 30, 8),
('Cooking Oil', 'litre', 18, 5),
('Milk', 'litre', 12, 6),
('Paneer', 'kg', 6, 2),
('Chicken', 'kg', 12, 4)
on conflict do nothing;

insert into public.coupons (code, discount_type, discount_value, min_order_value, max_uses, used_count, is_active, expires_at) values
('SAVOR10', 'percent', 10, 300, 100, 0, true, '2026-12-31 23:59:59+00'),
('FLAT50', 'flat', 50, 500, 100, 0, true, '2026-12-31 23:59:59+00')
on conflict (code) do nothing;

insert into public.app_settings (restaurant_name, address, phone, gstin)
select 'SAVOR Kitchen', '12, Brigade Road, Bengaluru - 560001', '+91 98765 43210', '29ABCDE1234F1Z5'
where not exists (select 1 from public.app_settings);

-- Add users:
-- 1. Create the user in Supabase Dashboard > Authentication > Users.
-- 2. Set metadata while creating the user, for example:
--    {"name":"Aditya Sen","role":"admin"}
-- 3. The trigger above creates public.profiles automatically.
-- 4. To change a role later, run:
-- update public.profiles set role = 'admin' where email = 'admin@example.com';
